# This file was generated by GoReleaser. DO NOT EDIT.
class Taskctl < Formula
  desc ""
  homepage "https://github.com/taskctl/taskctl"
  version "1.0.0-rc3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/taskctl/taskctl/releases/download/1.0.0-rc3/taskctl_1.0.0-rc3_darwin_amd64.tar.gz"
    sha256 "607de35f35ebb6973267caad940a3a265c306ff7b52919e3c5093c44bc74d400"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/taskctl/taskctl/releases/download/1.0.0-rc3/taskctl_1.0.0-rc3_linux_amd64.tar.gz"
      sha256 "63dbbb6a7e6a27959836fa9b45a0213ac1c22215a914ecaff62e5980777f019f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/taskctl/taskctl/releases/download/1.0.0-rc3/taskctl_1.0.0-rc3_linux_armv6.tar.gz"
        sha256 "7fb81ffb8cc4499fa25b1000eeddd5f5f5baee14843a51f16310a187d37abb0c"
      end
    end
  end

  def install
    bin.install "program"
    bash_completion.install "autocomplete/bash_completion.bash"
    zsh_completion.install "autocomplete/zsh_completion.zsh"
  end
end
