# This file was generated by GoReleaser. DO NOT EDIT.
class Taskctl < Formula
  desc ""
  homepage "https://github.com/taskctl/taskctl"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/taskctl/taskctl/releases/download/1.0.3/taskctl_1.0.3_darwin_amd64.tar.gz"
    sha256 "337f53e31f23c087e48bc000c391d26a42a78ee9e67ccf8e46a8d74998b92441"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/taskctl/taskctl/releases/download/1.0.3/taskctl_1.0.3_linux_amd64.tar.gz"
      sha256 "85b1d43112db139d92a0a672bc0319abbe4c08bd58786ed4b625279cd1e016f9"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/taskctl/taskctl/releases/download/1.0.3/taskctl_1.0.3_linux_armv6.tar.gz"
        sha256 "8b0610ffb1480734f3adcd0d82b70ccb840fa195e8fc055a7a10687fcbe8d472"
      end
    end
  end

  def install
    bin.install "program"
    bash_completion.install "autocomplete/bash_completion.bash"
    zsh_completion.install "autocomplete/zsh_completion.zsh"
  end
end
