# This file was generated by GoReleaser. DO NOT EDIT.
class Taskctl < Formula
  desc ""
  homepage "https://github.com/taskctl/taskctl"
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/taskctl/taskctl/releases/download/1.0.4/taskctl_1.0.4_darwin_amd64.tar.gz"
    sha256 "821bc44387689f92711ce48184ebfc5b71cb39c654638f0038c2bdddf5ed4498"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/taskctl/taskctl/releases/download/1.0.4/taskctl_1.0.4_linux_amd64.tar.gz"
      sha256 "7e0ec90c35e7c3a3570352118d14427a6b94718a057de895ad2592bfbe53df6d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/taskctl/taskctl/releases/download/1.0.4/taskctl_1.0.4_linux_armv6.tar.gz"
        sha256 "9f798cfb4d84d22defb8412166f4c6e291b7b6bd9c42748660b6f6f9c6593939"
      end
    end
  end

  def install
    bin.install "program"
    bash_completion.install "autocomplete/bash_completion.bash"
    zsh_completion.install "autocomplete/zsh_completion.zsh"
  end
end
